### ISSUE TITLE
pip 1.6 installation does not contain `ModelMultipleChoicePreference `

### ISSUE THREAD

**Issue by Haizzz** [EliotBerriot/django-dynamic-preferences#148]
I just tried to install this in a virtual environment with python3.6, Mac 10.13.6 with 
`pip install django-dynamic-preferences==1.6`

in my `dynamic_preferences_registry.py` file I tried to do the import:
```python
from dynamic_preferences.types import ModelMultipleChoicePreference
```
but that class doesn't seem to exist

Stack trace:
```
(env) [02:15 pm] anh@anhs-computer:(referral-criteria)unocart-backend $ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
    │                         └ <module 'sys' (built-in)>
    └ <function execute_from_command_line at 0x1035ed1e0>
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
    └ <django.core.management.ManagementUtility object at 0x1030f5ba8>
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
    └ <LazySettings "root.settings">
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
    │           └ 'INSTALLED_APPS'
    └ <LazySettings "root.settings">
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
    │               │        └ 'root.settings'
    │               └ <class 'django.conf.Settings'>
    └ <LazySettings "root.settings">
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          │                       └ <Settings "root.settings">
          └ <module 'importlib' from '/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/importlib/__init__.py'>
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │                      │    │        │        └ 0
           │                      │    │        └ None
           │                      │    └ 0
           │                      └ 'root.settings'
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/anh/Desktop/Github/unocart-backend/root/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/Users/anh/Desktop/Github/unocart-backend/root/celery.py", line 10, in <module>
    django.setup()
    └ <module 'django' from '/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/__init__.py'>
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    │             └ <LazySettings "root.settings">
    └ <django.apps.registry.Apps object at 0x1034ad518>
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
    └ <DynamicPreferencesConfig: dynamic_preferences>
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/dynamic_preferences/apps.py", line 20, in ready
    global_preferences_registry.autodiscover(app_names)
    │                                        └ ['rest_auth', 'rest_framework.authtoken', 'feedmee_user', 'channels', 'algoliasearch_django', 'db_fixtures', 'crispy_forms', 'gr...
    └ GlobalPreferenceRegistry()
  File "/Users/anh/Desktop/Github/unocart-backend/env/lib/python3.6/site-packages/persisting_theory/registries.py", line 107, in autodiscover
    module = __import__(package)
                        └ 'groceries_order.dynamic_preferences_registry'
  File "/Users/anh/Desktop/Github/unocart-backend/groceries_order/dynamic_preferences_registry.py", line 1, in <module>
    from dynamic_preferences.types import BooleanPreference, StringPreference, IntegerPreference, ModelMultipleChoicePreference
ImportError: cannot import name 'ModelMultipleChoicePreference'
```

**Comment by EliotBerriot** [comment]
Hi @Haizzz! That's normal: a release embarking this change has not been pushed to PyPi yet ;)

I'll try to do one soon, in the meantime, you can install from the specific commit instead (5e6e14f1d0db6d04d558b439f742cbe416741d95)

**Comment by Haizzz** [comment]
Thank you for that, I'll close the ticket then
