### ISSUE TITLE
Preferences not present in admin panel after flush or multiple selenium tests

### ISSUE THREAD

**Issue by ptrstn** [EliotBerriot/django-dynamic-preferences#150]
Hello,

I ran into a problem when running selenium tests. My preferences are gone when running more than one test case.

This happens with both pytest and python manage.py test. While the first test case *test_preferences_present* passes, the same exact test case *test_same_thing_again* fails, because the preferences are gone.

**tests.py**:
```python
from django.contrib.auth.models import User

from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from selenium.webdriver.firefox.webdriver import WebDriver

from dynamic_preferences.registries import global_preferences_registry

global_preferences = global_preferences_registry.manager()


class MySeleniumTests(StaticLiveServerTestCase):
    def setUp(self):
        self.selenium = WebDriver()
        self.selenium.implicitly_wait(10)
        self.user = User.objects.create_superuser("admin", "", "supersecurepass")

    def tearDown(self):
        self.selenium.quit()

    def test_preferences_present(self):
        assert global_preferences['my_preference'] is True
        self.selenium.get('%s%s' % (self.live_server_url, '/admin/'))
        username_input = self.selenium.find_element_by_id("id_username")
        username_input.send_keys('admin')
        password_input = self.selenium.find_element_by_id("id_password")
        password_input.send_keys('supersecurepass')
        self.selenium.find_element_by_xpath('//input[@value="Log in"]').click()
        self.selenium.find_element_by_link_text("Global preferences").click()
        self.selenium.find_element_by_link_text("my_preference")

    def test_same_thing_again(self):
        assert global_preferences['my_preference'] is True
        self.selenium.get('%s%s' % (self.live_server_url, '/admin/'))
        username_input = self.selenium.find_element_by_id("id_username")
        username_input.send_keys('admin')
        password_input = self.selenium.find_element_by_id("id_password")
        password_input.send_keys('supersecurepass')
        self.selenium.find_element_by_xpath('//input[@value="Log in"]').click()
        self.selenium.find_element_by_link_text("Global preferences").click()
        self.selenium.find_element_by_link_text("my_preference")
```

**dynamic_preferences_registry.py**:
```python
from dynamic_preferences.registries import global_preferences_registry
from dynamic_preferences.types import BooleanPreference


@global_preferences_registry.register
class MyPreference(BooleanPreference):
    name = 'my_preference'
    default = True
```

```bash
(venv) C:\Users\NoneOfYourBusiness\workspace\django\bla\bla>python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.E
======================================================================
ERROR: test_same_thing_again (exampleapp.tests.MySeleniumTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\NoneOfYourBusiness\workspace\django\bla\bla\exampleapp\tests.py", line 40, in test_same_thing_again
    self.selenium.find_element_by_link_text("my_preference")
  File "C:\Users\NoneOfYourBusiness\workspace\django\bla\bla\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\Users\NoneOfYourBusiness\workspace\django\bla\bla\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 966, in find_element
    'value': value})['value']
  File "C:\Users\NoneOfYourBusiness\workspace\django\bla\bla\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\NoneOfYourBusiness\workspace\django\bla\bla\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: my_preference


----------------------------------------------------------------------
Ran 2 tests in 26.012s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

Strangely the assertion
```python
assert global_preferences['my_preference'] is True
````
passes in both cases, so the preference should be at least somewhere present.

Same problem occurs when you do the following:
- do the things as described in the installation instructions
- go to admin panel and click on "Global preferences"
- *my_preference* is **present**
- do: ```python manage.py flush```
- do same steps again from above again:
    - go to admin panel and click on "Global preferences"
    - *my_preference* is **not present**

When checking the ```db.sqlite3``` file manually, then the ```dynamic_preferences_globalpreferencemodal``` is completely empty though.

I am not sure if I forgot to do something or if this is indeed a bug. If you need more information (like an example project) I am happy to provide these.

**Comment by EliotBerriot** [comment]
It's probably because the test runner flushes the database between each tests, and preferences are not recreated automatically until you actually access them. And preferences are cached as well, meaning `assert global_preferences['my_preference'] is True` will only query the cache.

I suggest you flush your cache as well as part of your test setup (cf https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/tests/test_manager.py#L16)

It should be good after that ;)

**Comment by EliotBerriot** [comment]
Another way would be to assign a value to the preference: `global_preferences['my_preference'] = True` would effectively create or update the pref in database, as well as cleaning the cache. But cleaning the cache between tests is good practice anyway ;)

**Comment by ptrstn** [comment]
Thank you for the quick response, clearing the cache did indeed fix the problem!
```
    def tearDown(self):
        caches['default'].clear()
```

Is this something that we should include in the documentation?
