### ISSUE TITLE
Wrong filename when using FilePreference and saving multiple times

### ISSUE THREAD

**Issue by saemideluxe** [EliotBerriot/django-dynamic-preferences#198]
Reproduce:
1. Create a new django project, add an admin user, an app and a single new file preference.
```
@global_preferences_registry.register
class Logo(FilePreference):
    name = "logo"
    default = None
```
2. Login to the admin backend and go to the page where you can edit the global preferences.
3. Upload a file for the logo field and save
4. Save again

**Expected result**
The path of the logo field should not change

**Actual result**
The path of the logo changes from ```dynamic_preferences/logo/<filename>``` to ```dynamic_preferences/logo/dynamic_preferences/logo/<filename>```

The problem seems to be that the function to_db in the FileSerializer does not distinguish whether the file is new or not. I have here a suggestion:

```
def to_db(self, f, **kwargs):
    if not f:
        return
    saved_path = f.name
    if not hasattr(f, "save"):
        path = os.path.join(self.preference.get_upload_path(), f.name)
        saved_path = self.preference.get_file_storage().save(path, f)

    return saved_path
```
When a new file is uploaded, it is an InMemoryUploadedFile which has no save method and the save method from the storage backend must is used. If the file is coming from the storage, there is a save method (which we do not need to call because the content has not changed).

Are you interested in a PR?

**Comment by EliotBerriot** [comment]
I'm definitely interested in a PR for this, thank you for spotting the bug.

Your suggested change sounds good too!

**Comment by saemideluxe** [comment]
Okay, could you give me some help with the tests?
I followed the instructions in CONTRIBUTING.rst (except using python3 -m venv .venv instead of mkvirtualenv, but activated the environment, also installed requirments-test.txt)
But when I come to step 5 I get a lot of error messages
```
$ flake8 dynamic_preferences tests
dynamic_preferences/registries.py:2:1: F401 'django.apps.apps' imported but unused
dynamic_preferences/registries.py:15:1: E402 module level import not at top of file
dynamic_preferences/registries.py:16:1: E402 module level import not at top of file
dynamic_preferences/registries.py:17:1: E402 module level import not at top of file
dynamic_preferences/registries.py:18:1: E402 module level import not at top of file
dynamic_preferences/registries.py:19:1: E402 module level import not at top of file
dynamic_preferences/registries.py:19:1: F401 '.preferences.EMPTY_SECTION' imported but unused
dynamic_preferences/registries.py:81:101: E501 line too long (117 > 100 characters)
dynamic_preferences/registries.py:88:101: E501 line too long (106 > 100 characters)
dynamic_preferences/registries.py:152:101: E501 line too long (136 > 100 characters)
dynamic_preferences/registries.py:154:101: E501 line too long (122 > 100 characters)
...
...
```

```
$ python setup.py test
running test
running egg_info
writing django_dynamic_preferences.egg-info/PKG-INFO
writing dependency_links to django_dynamic_preferences.egg-info/dependency_links.txt
writing requirements to django_dynamic_preferences.egg-info/requires.txt
writing top-level names to django_dynamic_preferences.egg-info/top_level.txt
reading manifest file 'django_dynamic_preferences.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.png' under directory 'dynamic_preferences'
warning: no files found matching '*.gif' under directory 'dynamic_preferences'
warning: no files found matching '*js' under directory 'dynamic_preferences'
warning: no files found matching '*.css' under directory 'dynamic_preferences'
warning: no files found matching '*jpg' under directory 'dynamic_preferences'
warning: no files found matching '*jpeg' under directory 'dynamic_preferences'
warning: no files found matching '*svg' under directory 'dynamic_preferences'
writing manifest file 'django_dynamic_preferences.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    "Programming Language :: Python :: 3.4",
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/sam/git/django-dynamic-preferences/dynamic_preferences/processors.py", line 1, in <module>
    from .registries import global_preferences_registry as gpr
  File "/home/sam/git/django-dynamic-preferences/dynamic_preferences/registries.py", line 18, in <module>
    from .types import StringPreference
  File "/home/sam/git/django-dynamic-preferences/dynamic_preferences/types.py", line 11, in <module>
    from .preferences import AbstractPreference, Section
  File "/home/sam/git/django-dynamic-preferences/dynamic_preferences/preferences.py", line 48, in <module>
    EMPTY_SECTION = Section(None)
  File "/home/sam/git/django-dynamic-preferences/dynamic_preferences/preferences.py", line 39, in __init__
    if preferences_settings.VALIDATE_NAMES and name:
  File "/home/sam/git/django-dynamic-preferences/dynamic_preferences/settings.py", line 56, in __getattr__
    val = self.user_settings[attr]
  File "/home/sam/git/django-dynamic-preferences/dynamic_preferences/settings.py", line 48, in user_settings
    return getattr(settings, SETTINGS_ATTR, {})
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/conf/__init__.py", line 61, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DYNAMIC_PREFERENCES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

```
$ tox
GLOB sdist-make: /home/sam/git/django-dynamic-preferences/setup.py
py27-django-111 inst-nodeps: /home/sam/git/django-dynamic-preferences/.tox/.tmp/package/1/django-dynamic-preferences-1.8.1.zip
py27-django-111 installed: atomicwrites==1.3.0,attrs==19.3.0,certifi==2019.11.28,cffi==1.13.2,chardet==3.0.4,configparser==4.0.2,contextlib2==0.6.0.post1,coverage==5.0.2,coveralls==1.10.0,cryptography==2.8,Django==1.11.27,django-dynamic-preferences==1.8.1,django-nose==1.4.6,djangorestframework==3.9.4,docopt==0.6.2,entrypoints==0.3,enum34==1.1.6,filelock==3.0.12,flake8==3.7.9,funcsigs==1.0.2,functools32==3.2.3.post2,idna==2.8,importlib-metadata==1.3.0,ipaddress==1.0.23,mccabe==0.6.1,mock==3.0.5,more-itertools==5.0.0,nose==1.3.7,packaging==20.0,pathlib2==2.3.5,persisting-theory==0.2.1,pkg-resources==0.0.0,pluggy==0.13.1,py==1.8.1,pycodestyle==2.5.0,pycparser==2.19,pyflakes==2.1.1,pyOpenSSL==19.1.0,pyparsing==2.4.6,pytest==4.6.9,pytest-cov==2.8.1,pytest-django==3.7.0,pytest-sugar==0.9.2,pytz==2019.3,requests==2.22.0,scandir==1.10.0,six==1.13.0,termcolor==1.1.0,toml==0.10.0,tox==3.14.3,typing==3.7.4.1,urllib3==1.25.7,virtualenv==16.7.9,wcwidth==0.1.8,zipp==0.6.0
py27-django-111 run-test-pre: PYTHONHASHSEED='3749002042'
py27-django-111 run-test: commands[0] | pytest
Test session starts (platform: linux2, Python 2.7.17, pytest 4.6.9, pytest-sugar 0.9.2)
cachedir: .tox/py27-django-111/.pytest_cache
Django settings: tests.settings (from ini file)
rootdir: /home/sam/git/django-dynamic-preferences, inifile: pytest.ini
plugins: sugar-0.9.2, django-3.7.0, cov-2.8.1
collecting ...
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― .eggs/persisting_theory-0.2.1-py3.7.egg/tests/test_registries.py ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ImportError while importing test module '/home/sam/git/django-dynamic-preferences/.eggs/persisting_theory-0.2.1-py3.7.egg/tests/test_registries.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ImportError: No module named test_registries

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― .eggs/persisting_theory-0.2.1-py3.7.egg/tests/tests.py ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ImportError while importing test module '/home/sam/git/django-dynamic-preferences/.eggs/persisting_theory-0.2.1-py3.7.egg/tests/tests.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ImportError: No module named tests

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
...
...
```

I also tried running runtests.py (which would solve some of the above problems with ```python setup.py test``` but I still get 29 errors, like this one:

```
======================================================================
ERROR: test_user_preference_form_is_bound_with_current_user (tests.test_user_preferences.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sam/git/django-dynamic-preferences/tests/test_user_preferences.py", line 131, in test_user_preference_form_is_bound_with_current_user
    "dynamic_preferences:user.section", kwargs={'section': 'misc'})
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/urls/base.py", line 55, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/urls/resolvers.py", line 521, in app_dict
    self._populate()
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/urls/resolvers.py", line 455, in _populate
    for url_pattern in reversed(self.url_patterns):
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sam/git/django-dynamic-preferences/.venv/lib/python3.7/site-packages/Django-3.0.2-py3.7.egg/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sam/git/django-dynamic-preferences/tests/urls.py", line 12, in <module>
    router.register(r'global', GlobalPreferencesViewSet, base_name='global')
TypeError: register() got an unexpected keyword argument 'base_name'

----------------------------------------------------------------------
```

Can you tell me what I am doing wrong? Do I need to use python 2 or does this only work with mkvirtualenv? Thanks.

**Comment by EliotBerriot** [comment]
I usually run the tests like this on my machine: `tox -e py37-django-22`, I think the CONTRIBUTING.rst part you're referring too is still here from the project template we used initially :upside_down_face:
