### ISSUE TITLE
Install via requirements file fails

### ISSUE THREAD

**Issue by EliotBerriot** [EliotBerriot/django-dynamic-preferences#3]
Installing with a requirements file such as:

    django
    django-dynamic-preferences

Fails with the following stack trace : 

    Collecting django (from -r requirements.txt (line 1))
      Using cached Django-1.8.3-py2.py3-none-any.whl
    Collecting django-dynamic-preferences (from -r requirements.txt (line 2))
      Downloading django-dynamic-preferences-0.4.3.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-9g6wc0w2/django-dynamic-preferences/setup.py", line 7, in <module>
            import dynamic_preferences
          File "/tmp/pip-build-9g6wc0w2/django-dynamic-preferences/dynamic_preferences/__init__.py", line 1, in <module>
            from .dynamic_preferences_registry import user_preferences_registry, global_preferences_registry
          File "/tmp/pip-build-9g6wc0w2/django-dynamic-preferences/dynamic_preferences/dynamic_preferences_registry.py", line 1, in <module>
            from .registries import PreferenceRegistry, PerInstancePreferenceRegistry
          File "/tmp/pip-build-9g6wc0w2/django-dynamic-preferences/dynamic_preferences/registries.py", line 3, in <module>
            from django.conf import settings
        ImportError: No module named 'django'

This is caused by django settings imported in the `__init__.py` file.

**Comment by willseward** [comment]
I'm looking at this now. I think this can be solved with a __future__ import statement.
